export const SURAH_METADATA = {
  1: { name: 'Al-Fatihah', arabic: 'الفاتحة', english: 'The Opening' },
  2: { name: 'Al-Baqarah', arabic: 'البقرة', english: 'The Cow' },
  3: { name: "Ali 'Imran", arabic: 'آل عمران', english: 'Family of Imran' },
  4: { name: 'An-Nisa', arabic: 'النساء', english: 'The Women' },
  5: { name: "Al-Ma'idah", arabic: 'المائدة', english: 'The Table Spread' },
  6: { name: "Al-An'am", arabic: 'الأنعام', english: 'The Cattle' },
  7: { name: "Al-A'raf", arabic: 'الأعراف', english: 'The Heights' },
  8: { name: 'Al-Anfal', arabic: 'الأنفال', english: 'The Spoils of War' },
  9: { name: 'At-Tawbah', arabic: 'التوبة', english: 'The Repentance' },
  10: { name: 'Yunus', arabic: 'يونس', english: 'Jonah' },
  11: { name: 'Hud', arabic: 'هود', english: 'Hud' },
  12: { name: 'Yusuf', arabic: 'يوسف', english: 'Joseph' },
  13: { name: "Ar-Ra'd", arabic: 'الرعد', english: 'The Thunder' },
  14: { name: 'Ibrahim', arabic: 'إبراهيم', english: 'Abraham' },
  15: { name: 'Al-Hijr', arabic: 'الحجر', english: 'The Rocky Tract' },
  16: { name: 'An-Nahl', arabic: 'النحل', english: 'The Bee' },
  17: { name: 'Al-Isra', arabic: 'الإسراء', english: 'The Night Journey' },
  18: { name: 'Al-Kahf', arabic: 'الكهف', english: 'The Cave' },
  19: { name: 'Maryam', arabic: 'مريم', english: 'Mary' },
  20: { name: 'Taha', arabic: 'طه', english: 'Ta-Ha' },
  21: { name: 'Al-Anbiya', arabic: 'الأنبياء', english: 'The Prophets' },
  22: { name: 'Al-Hajj', arabic: 'الحج', english: 'The Pilgrimage' },
  23: { name: "Al-Mu'minun", arabic: 'المؤمنون', english: 'The Believers' },
  24: { name: 'An-Nur', arabic: 'النور', english: 'The Light' },
  25: { name: 'Al-Furqan', arabic: 'الفرقان', english: 'The Criterion' },
  26: { name: "Ash-Shu'ara", arabic: 'الشعراء', english: 'The Poets' },
  27: { name: 'An-Naml', arabic: 'النمل', english: 'The Ant' },
  28: { name: 'Al-Qasas', arabic: 'القصص', english: 'The Stories' },
  29: { name: 'Al-Ankabut', arabic: 'العنكبوت', english: 'The Spider' },
  30: { name: 'Ar-Rum', arabic: 'الروم', english: 'The Romans' },
  31: { name: 'Luqman', arabic: 'لقمان', english: 'Luqman' },
  32: { name: 'As-Sajdah', arabic: 'السجدة', english: 'The Prostration' },
  33: { name: 'Al-Ahzab', arabic: 'الأحزاب', english: 'The Combined Forces' },
  34: { name: 'Saba', arabic: 'سبأ', english: 'Sheba' },
  35: { name: 'Fatir', arabic: 'فاطر', english: 'Originator' },
  36: { name: 'Ya-Sin', arabic: 'يس', english: 'Ya Sin' },
  37: { name: 'As-Saffat', arabic: 'الصافات', english: 'Those Who Set The Ranks' },
  38: { name: 'Sad', arabic: 'ص', english: 'The Letter Sad' },
  39: { name: 'Az-Zumar', arabic: 'الزمر', english: 'The Troops' },
  40: { name: 'Ghafir', arabic: 'غافر', english: 'The Forgiver' },
  41: { name: 'Fussilat', arabic: 'فصلت', english: 'Explained In Detail' },
  42: { name: 'Ash-Shura', arabic: 'الشورى', english: 'The Consultation' },
  43: { name: 'Az-Zukhruf', arabic: 'الزخرف', english: 'The Ornaments of Gold' },
  44: { name: 'Ad-Dukhan', arabic: 'الدخان', english: 'The Smoke' },
  45: { name: 'Al-Jathiyah', arabic: 'الجاثية', english: 'The Crouching' },
  46: { name: 'Al-Ahqaf', arabic: 'الأحقاف', english: 'The Wind-Curved Sandhills' },
  47: { name: 'Muhammad', arabic: 'محمد', english: 'Muhammad' },
  48: { name: 'Al-Fath', arabic: 'الفتح', english: 'The Victory' },
  49: { name: 'Al-Hujurat', arabic: 'الحجرات', english: 'The Rooms' },
  50: { name: 'Qaf', arabic: 'ق', english: 'The Letter Qaf' },
  51: { name: 'Adh-Dhariyat', arabic: 'الذاريات', english: 'The Winnowing Winds' },
  52: { name: 'At-Tur', arabic: 'الطور', english: 'The Mount' },
  53: { name: 'An-Najm', arabic: 'النجم', english: 'The Star' },
  54: { name: 'Al-Qamar', arabic: 'القمر', english: 'The Moon' },
  55: { name: 'Ar-Rahman', arabic: 'الرحمن', english: 'The Beneficent' },
  56: { name: "Al-Waqi'ah", arabic: 'الواقعة', english: 'The Inevitable' },
  57: { name: 'Al-Hadid', arabic: 'الحديد', english: 'The Iron' },
  58: { name: 'Al-Mujadila', arabic: 'المجادلة', english: 'The Pleading Woman' },
  59: { name: 'Al-Hashr', arabic: 'الحشر', english: 'The Exile' },
  60: { name: 'Al-Mumtahanah', arabic: 'الممتحنة', english: 'She That Is To Be Examined' },
  61: { name: 'As-Saff', arabic: 'الصف', english: 'The Ranks' },
  62: { name: "Al-Jumu'ah", arabic: 'الجمعة', english: 'The Congregation' },
  63: { name: 'Al-Munafiqun', arabic: 'المنافقون', english: 'The Hypocrites' },
  64: { name: 'At-Taghabun', arabic: 'التغابن', english: 'The Mutual Disillusion' },
  65: { name: 'At-Talaq', arabic: 'الطلاق', english: 'The Divorce' },
  66: { name: 'At-Tahrim', arabic: 'التحريم', english: 'The Prohibition' },
  67: { name: 'Al-Mulk', arabic: 'الملك', english: 'The Sovereignty' },
  68: { name: 'Al-Qalam', arabic: 'القلم', english: 'The Pen' },
  69: { name: 'Al-Haqqah', arabic: 'الحاقة', english: 'The Reality' },
  70: { name: "Al-Ma'arij", arabic: 'المعارج', english: 'The Ascending Stairways' },
  71: { name: 'Nuh', arabic: 'نوح', english: 'Noah' },
  72: { name: 'Al-Jinn', arabic: 'الجن', english: 'The Jinn' },
  73: { name: 'Al-Muzzammil', arabic: 'المزمل', english: 'The Enshrouded One' },
  74: { name: 'Al-Muddaththir', arabic: 'المدثر', english: 'The Cloaked One' },
  75: { name: 'Al-Qiyamah', arabic: 'القيامة', english: 'The Resurrection' },
  76: { name: 'Al-Insan', arabic: 'الإنسان', english: 'Man' },
  77: { name: 'Al-Mursalat', arabic: 'المرسلات', english: 'The Emissaries' },
  78: { name: 'An-Naba', arabic: 'النبأ', english: 'The Tidings' },
  79: { name: "An-Nazi'at", arabic: 'النازعات', english: 'Those Who Drag Forth' },
  80: { name: "'Abasa", arabic: 'عبس', english: 'He Frowned' },
  81: { name: 'At-Takwir', arabic: 'التكوير', english: 'The Overthrowing' },
  82: { name: 'Al-Infitar', arabic: 'الانفطار', english: 'The Cleaving' },
  83: { name: 'Al-Mutaffifin', arabic: 'المطففين', english: 'The Defrauding' },
  84: { name: 'Al-Inshiqaq', arabic: 'الانشقاق', english: 'The Splitting Open' },
  85: { name: 'Al-Buruj', arabic: 'البروج', english: 'The Constellations' },
  86: { name: 'At-Tariq', arabic: 'الطارق', english: 'The Nightcommer' },
  87: { name: "Al-A'la", arabic: 'الأعلى', english: 'The Most High' },
  88: { name: 'Al-Ghashiyah', arabic: 'الغاشية', english: 'The Overwhelming' },
  89: { name: 'Al-Fajr', arabic: 'الفجر', english: 'The Dawn' },
  90: { name: 'Al-Balad', arabic: 'البلد', english: 'The City' },
  91: { name: 'Ash-Shams', arabic: 'الشمس', english: 'The Sun' },
  92: { name: 'Al-Layl', arabic: 'الليل', english: 'The Night' },
  93: { name: 'Ad-Duhaa', arabic: 'الضحى', english: 'The Morning Hours' },
  94: { name: 'Ash-Sharh', arabic: 'الشرح', english: 'The Relief' },
  95: { name: 'At-Tin', arabic: 'التين', english: 'The Fig' },
  96: { name: "Al-'Alaq", arabic: 'العلق', english: 'The Clot' },
  97: { name: 'Al-Qadr', arabic: 'القدر', english: 'The Power' },
  98: { name: 'Al-Bayyinah', arabic: 'البينة', english: 'The Clear Proof' },
  99: { name: 'Az-Zalzalah', arabic: 'الزلزلة', english: 'The Earthquake' },
  100: { name: "Al-'Adiyat", arabic: 'العاديات', english: 'The Courser' },
  101: { name: "Al-Qari'ah", arabic: 'القارعة', english: 'The Calamity' },
  102: { name: 'At-Takathur', arabic: 'التكاثر', english: 'The Rivalry in World Increase' },
  103: { name: "Al-'Asr", arabic: 'العصر', english: 'The Declining Day' },
  104: { name: 'Al-Humazah', arabic: 'الهمزة', english: 'The Traducer' },
  105: { name: 'Al-Fil', arabic: 'الفيل', english: 'The Elephant' },
  106: { name: 'Quraysh', arabic: 'قريش', english: 'Quraysh' },
  107: { name: "Al-Ma'un", arabic: 'الماعون', english: 'The Small Kindness' },
  108: { name: 'Al-Kawthar', arabic: 'الكوثر', english: 'The Abundance' },
  109: { name: 'Al-Kafirun', arabic: 'الكافرون', english: 'The Disbelievers' },
  110: { name: 'An-Nasr', arabic: 'النصر', english: 'The Divine Support' },
  111: { name: 'Al-Masad', arabic: 'المسد', english: 'The Palm Fiber' },
  112: { name: 'Al-Ikhlas', arabic: 'الإخلاص', english: 'The Sincerity' },
  113: { name: 'Al-Falaq', arabic: 'الفلق', english: 'The Daybreak' },
  114: { name: 'An-Nas', arabic: 'الناس', english: 'Mankind' },
};
